services:
  postgres:
    image: postgres:17
    container_name: fast-feet-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fast_feet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:17
    container_name: fast-feet-db-test
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fast_feet_test

volumes:
  postgres_data:
