[project]
name = "codams"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "krishna0915", email = "kirmada.1509@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "load-dotenv>=0.1.0",
    "openai>=3.22.0",
    "pytest>=9.1.1",
]

[project.scripts]
codams = "codams:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
